### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by dicook** [TengMCing/spotoroo#1]
We need a cute name for the package. I've been using Australian animals and birds, and plants. 

From an acronym creator
PARCH sPAtiotempoRal Clustering of Hotspots
STITCH SpaTIoTemporal Clustering Hotspots

From Atlas of Living Australia
fireoak Fire Oak Allocasuarina littoralis
potoroo sPatiOtemporal clusTering in R of hOt spOt (or maybe spotoroo)

**Comment by TengMCing** [comment]
That is the thing I want to discuss with you today 😅

**Comment by TengMCing** [comment]
"spotoroo" is accepted.
