### ISSUE TITLE
win_builder 1 note

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/spotoroo#10]
* using log directory 'd:/RCompile/CRANguest/R-release/spotoroo.Rcheck'
* using R version 4.0.4 (2021-02-15)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'spotoroo/DESCRIPTION' ... OK
* this is package 'spotoroo' version '0.1.0'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Weihao Li <llreczx@gmail.com>'

New submission

Possibly mis-spelled words in DESCRIPTION:
  Spatiotemporal (2:8)

Found the following (possibly) invalid file URIs:
  URI: weihao.li@monash.edu
    From: man/spotoroo.Rd
  URI: dicook@monash.edu
    From: man/spotoroo.Rd
  URI: emdodwell@gmail.com
    From: man/spotoroo.Rd

The Title field should be in title case. Current version is:
'Spatiotemporal clustering of satellite hot spot data'
In title case that is:
'Spatiotemporal Clustering of Satellite Hot Spot Data'

The Description field should not start with the package name,
  'This package' or similar.
* checking package namespace information ... OK

---
I fixed the title case, the description field and the URIs.

How about the word "Spatiotemporal", do I need to replace it with another word?

@dicook 
@emdodwell

**Comment by emdodwell** [comment]
I think spatiotemporal is fine -- that's the commonly accepted spelling.

In "Description", correct "temporarily" -> "temporally" (wouldn't be picked up by spell-checker).

**Comment by dicook** [comment]
Spatiotemporal is a legitimate spelling. You can make a note about this in the file cran-comments.md. You create this file in order to make the submission, with notes on how you have checked the package prior to submitting and any comments like this on the checks.

I don’t see where it is getting the URIs from. Your email address is not weihao.li@monash.edu in the DESCRIPTION file. Where is this coming from? Its in spotoroo.Rd, but its not clear how this file is generated or whether its an oldd file that needs removing or regenerating. 

> On 17 Feb 2021, at 12:31 pm, Weihao (Patrick) Li <notifications@github.com> wrote:
> 
> 
> 	• using log directory 'd:/RCompile/CRANguest/R-release/spotoroo.Rcheck'
> 	• using R version 4.0.4 (2021-02-15)
> 	• using platform: x86_64-w64-mingw32 (64-bit)
> 	• using session charset: ISO8859-1
> 	• checking for file 'spotoroo/DESCRIPTION' ... OK
> 	• this is package 'spotoroo' version '0.1.0'
> 	• package encoding: UTF-8
> 	• checking CRAN incoming feasibility ... NOTE
> Maintainer: 'Weihao Li llreczx@gmail.com'
> New submission
> 
> Possibly mis-spelled words in DESCRIPTION:
> Spatiotemporal (2:8)
> 
> Found the following (possibly) invalid file URIs:
> URI: weihao.li@monash.edu
> From: man/spotoroo.Rd
> URI: dicook@monash.edu
> From: man/spotoroo.Rd
> URI: emdodwell@gmail.com
> From: man/spotoroo.Rd
> 
> The Title field should be in title case. Current version is:
> 'Spatiotemporal clustering of satellite hot spot data'
> In title case that is:
> 'Spatiotemporal Clustering of Satellite Hot Spot Data'
> 
> The Description field should not start with the package name,
> 'This package' or similar.
> 
> 	• checking package namespace information ... OK
> I fixed the title case, the description field and the URIs.
> 
> How about the word "Spatiotemporal", do I need to replace it with another word?
> 
> @dicook
> @emdodwell
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
visnut@gmail.com

**Comment by TengMCing** [comment]
The invalid file URIs is because I used \url{} instead of \email{} for the email address.
