### ISSUE TITLE
Error in Fedora Linux, R-devel, clang, gfortran

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/spotoroo#11]
The R CMD check fails in Fedora Linux, R-devel, clang, gfortran.
It passes another Linux version - Ubuntu Linux 20.04.1 LTS, R-release, GCC

The error is caused by the installation of the `sf` package.
Here is the detail message.

```
#> * installing *source* package ‘sf’ ...

3156#> ** package ‘sf’ successfully unpacked and MD5 sums checked

3157#> ** using staged installation

3158#> configure: CC: /usr/bin/clang

3159#> configure: CXX: /usr/bin/clang++

3160#> checking for gdal-config... /usr/bin/gdal-config

3161#> checking gdal-config usability... yes

3162#> configure: GDAL: 3.1.4

3163#> checking GDAL version >= 2.0.1... yes

3164#> checking for gcc... /usr/bin/clang

3165#> checking whether the C compiler works... yes

3166#> checking for C compiler default output file name... a.out

3167#> checking for suffix of executables...

3168#> checking whether we are cross compiling... no

3169#> checking for suffix of object files... o

3170#> checking whether we are using the GNU C compiler... yes

3171#> checking whether /usr/bin/clang accepts -g... yes

3172#> checking for /usr/bin/clang option to accept ISO C89... none needed

3173#> checking how to run the C preprocessor... cpp

3174#> checking for grep that handles long lines and -e... /usr/bin/grep

3175#> checking for egrep... /usr/bin/grep -E

3176#> checking for ANSI C header files... yes

3177#> checking for sys/types.h... yes

3178#> checking for sys/stat.h... yes

3179#> checking for stdlib.h... yes

3180#> checking for string.h... yes

3181#> checking for memory.h... yes

3182#> checking for strings.h... yes

3183#> checking for inttypes.h... yes

3184#> checking for stdint.h... yes

3185#> checking for unistd.h... yes

3186#> checking gdal.h usability... yes

3187#> checking gdal.h presence... yes

3188#> checking for gdal.h... yes

3189#> checking GDAL: linking with --libs only... yes

3190#> checking GDAL: /usr/share/gdal/pcs.csv readable... no

3191#> checking GDAL: checking whether PROJ is available for linking:... yes

3192#> checking GDAL: checking whether PROJ is available fur running:... yes

3193#> configure: GDAL: 3.1.4

3194#> checking proj.h usability... no

3195#> checking proj.h presence... no

3196#> checking for proj.h... no

3197#> checking proj_api.h usability... no

3198#> checking proj_api.h presence... no

3199#> checking for proj_api.h... no

3200#> configure: error: proj_api.h not found in standard or given locations.

3201#> ERROR: configuration failed for package ‘sf’
```

---

Honestly, I don't know how to resolve it. It can be due to the dependencies of the `sf` package.

I am giving it a second try.

**Comment by TengMCing** [comment]
I am considering completely dropping the function `plot_vic_map()` and also do not depend on `sf` anymore. It is such a complicated package that needs complex dependencies.

**Comment by dicook** [comment]
I think make it a suggests instead of a dependency would be a good solution.

> On 17 Feb 2021, at 4:51 pm, Weihao (Patrick) Li <notifications@github.com> wrote:
> 
> 
> I am considering completely dropping the function plot_vic_map() and also do not depend on sf anymore. It is such a complicated package that needs complex dependencies.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
visnut@gmail.com

**Comment by TengMCing** [comment]
It is already a suggests. The `check_rhub()` or `check_for_cran()` automatically force the machine to install all suggested packages. If I turn off this option, `testthat` will not be installed and no check on tests will be performed. 

The most I am concerning is when I submit it to CRAN, it might also force the machine to install all suggested package which will end up throwing an error because of unsuccessful installation of `sf`.

Therefore, I want to remove all `sf` related components from the package and only use it in the vignette since it can be built locally and I can prevent the remote machine from running it by checking the namespace.

**Comment by dicook** [comment]
check https://github.com/srkobakian/sugarbag because Steff’s package successfully made it onto CRAN

> On 17 Feb 2021, at 5:12 pm, Weihao (Patrick) Li <notifications@github.com> wrote:
> 
> 
> It is already a suggests. The check_rhub() or check_for_cran() automatically force the machine to install all suggested packages. If I turn off this option, testthat will not be installed and not check on tests will be performed.
> 
> The most I am concerning is when I submit it to CRAN, it might also force the machine to install all suggested package which will end up throwing an error because of unsuccessful installation of sf.
> 
> Therefore, I want to remove all sf related components from the package and only use it in the vignette since it can be built locally and I can prevent the remote machine from running it by checking the namespace.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
visnut@gmail.com

**Comment by TengMCing** [comment]
I downloaded `sugarbag_0.1.3.tar.gz`, submitted it to Rhub, and ran it on Fedora Linux, R-devel, clang, gfortran.

I got exactly same error. 

So, it must be something wrong with the `sf` package on this platform.

```
#> * installing *source* package ‘sf’ ...

3245#> ** package ‘sf’ successfully unpacked and MD5 sums checked

3246#> ** using staged installation

3247#> configure: CC: /usr/bin/clang

3248#> configure: CXX: /usr/bin/clang++

3249#> checking for gdal-config... /usr/bin/gdal-config

3250#> checking gdal-config usability... yes

3251#> configure: GDAL: 3.1.4

3252#> checking GDAL version >= 2.0.1... yes

3253#> checking for gcc... /usr/bin/clang

3254#> checking whether the C compiler works... yes

3255#> checking for C compiler default output file name... a.out

3256#> checking for suffix of executables...

3257#> checking whether we are cross compiling... no

3258#> checking for suffix of object files... o

3259#> checking whether we are using the GNU C compiler... yes

3260#> checking whether /usr/bin/clang accepts -g... yes

3261#> checking for /usr/bin/clang option to accept ISO C89... none needed

3262#> checking how to run the C preprocessor... cpp

3263#> checking for grep that handles long lines and -e... /usr/bin/grep

3264#> checking for egrep... /usr/bin/grep -E

3265#> checking for ANSI C header files... yes

3266#> checking for sys/types.h... yes

3267#> checking for sys/stat.h... yes

3268#> checking for stdlib.h... yes

3269#> checking for string.h... yes

3270#> checking for memory.h... yes

3271#> checking for strings.h... yes

3272#> checking for inttypes.h... yes

3273#> checking for stdint.h... yes

3274#> checking for unistd.h... yes

3275#> checking gdal.h usability... yes

3276#> checking gdal.h presence... yes

3277#> checking for gdal.h... yes

3278#> checking GDAL: linking with --libs only... yes

3279#> checking GDAL: /usr/share/gdal/pcs.csv readable... no

3280#> checking GDAL: checking whether PROJ is available for linking:... yes

3281#> checking GDAL: checking whether PROJ is available fur running:... yes

3282#> configure: GDAL: 3.1.4

3283#> checking proj.h usability... no

3284#> checking proj.h presence... no

3285#> checking for proj.h... no

3286#> checking proj_api.h usability... no

3287#> checking proj_api.h presence... no

3288#> checking for proj_api.h... configure: error: proj_api.h not found in standard or given locations.

3289#> no

3290#> ERROR: configuration failed for package ‘sf’

3291#> * removing ‘/home/docker/R/sf’
```

**Comment by dicook** [comment]
So you are likely ok with CRAN

**Comment by TengMCing** [comment]
Yeah, It could also be caused by  Rhub's VM. Considering `sugarbag` just passed the CRAN check on Feb 15, I think it is OK to ignore this error.

**Comment by TengMCing** [comment]
After testing R-hub's servers many times, I noticed that the inconsistency of their behaviours. It could have completely different results for an identical test.  Not sure what causes this, dependencies versions, OS versions, access rights, system setup or bugs. Anyway, it is not a very reliable testing service.
