### ISSUE TITLE
Examples > 5s

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/spotoroo#12]
On windows and mac, the running time of the examples is acceptable. However, on Linux, it doubles the running time which exceeds 5 seconds. Should I disable all time-consuming examples?

**Comment by dicook** [comment]
Yes, if needed

> On 17 Feb 2021, at 4:01 pm, Weihao (Patrick) Li <notifications@github.com> wrote:
> 
> 
> On windows and mac, the running time of the examples is acceptable. However, on Linux, it doubles the running time which exceeds 5 seconds. Should I disable all time-consuming examples?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
visnut@gmail.com

**Comment by TengMCing** [comment]
disabled
