### ISSUE TITLE
One good news and one bad news

### ISSUE THREAD

**Issue by TengMCing** [TengMCing/spotoroo#16]
I received an email saying that the package is on its way to CRAN. ✨🎉😃🎉✨

Now we can access the CRAN webpage at 

[https://cran.r-project.org/web/packages/spotoroo/index.html](https://cran.r-project.org/web/packages/spotoroo/index.html)

The bad news is it failed on r-patched-solaris-x86:

```
Version: 0.1.0
Check: examples
Result: ERROR
    Running examples in ‘spotoroo-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: plot_vic_map
    > ### Title: Plotting map of Victoria, Australia
    > ### Aliases: plot_vic_map
    >
    > ### ** Examples
    >
    > if (requireNamespace("sf", quietly = TRUE)) {
    + plot_vic_map()
    + }
    Warning in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy, :
     GDAL Error 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
    Error in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy, :
     OGRCreateCoordinateTransformation() returned NULL: PROJ available?
    Calls: <Anonymous> ... st_transform.sfc -> st_sfc -> structure -> CPL_transform
    Execution halted
Flavor: r-patched-solaris-x86

Version: 0.1.0
Check: re-building of vignette outputs
Result: WARN
    Error(s) in re-building vignettes:
     ...
    --- re-building ‘Clustering-hot-spots.Rmd’ using rmarkdown
    Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
    Quitting from lines 61-67 (Clustering-hot-spots.Rmd)
    Error: processing vignette 'Clustering-hot-spots.Rmd' failed with diagnostics:
    OGRCreateCoordinateTransformation() returned NULL: PROJ available?
    --- failed re-building ‘Clustering-hot-spots.Rmd’
    
    SUMMARY: processing the following file failed:
     ‘Clustering-hot-spots.Rmd’
    
    Error: Vignette re-building failed.
    Execution halted
Flavor: r-patched-solaris-x86
```

---

The possibilities are:

1. The CRAN machine had an older version of PROJ, it failed to transform the built-in sf dataset
2. The CRAN machine was unstable temporally 

For 1, I may need to follow this GitHub issue https://github.com/r-spatial/sf/issues/1419 to resolve the problem. I have to fix the problem before 2021-04-05 to safely retain the package on CRAN.

**Comment by dicook** [comment]
😃

> On 23 Mar 2021, at 10:08 am, Weihao (Patrick) Li ***@***.***> wrote:
> 
> 
> I received an email saying that the package is on its way to CRAN. ✨🎉😃🎉✨
> 
> Now we can access the CRAN webpage at
> 
> https://cran.r-project.org/web/packages/spotoroo/index.html
> 
> The bad news is it failed on r-patched-solaris-x86:
> 
> Version: 0.1.0
> Check: examples
> Result: ERROR
>     Running examples in ‘spotoroo-Ex.R’ failed
>     The error most likely occurred in:
>     
>     > ### Name: plot_vic_map
>     > ### Title: Plotting map of Victoria, Australia
>     > ### Aliases: plot_vic_map
>     >
>     > ### ** Examples
>     >
>     > if (requireNamespace("sf", quietly = TRUE)) {
>     + plot_vic_map()
>     + }
>     Warning in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy, :
>      GDAL Error 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
>     Error in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy, :
>      OGRCreateCoordinateTransformation() returned NULL: PROJ available?
>     Calls: <Anonymous> ... st_transform.sfc -> st_sfc -> structure -> CPL_transform
>     Execution halted
> Flavor: r-patched-solaris-x86
> 
> Version: 0.1.0
> Check: re-building of vignette outputs
> Result: WARN
>     Error(s) in re-building vignettes:
>      ...
>     --- re-building ‘Clustering-hot-spots.Rmd’ using rmarkdown
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Quitting from lines 61-67 (Clustering-hot-spots.Rmd)
>     Error: processing vignette 'Clustering-hot-spots.Rmd' failed with diagnostics:
>     OGRCreateCoordinateTransformation() returned NULL: PROJ available?
>     --- failed re-building ‘Clustering-hot-spots.Rmd’
>     
>     SUMMARY: processing the following file failed:
>      ‘Clustering-hot-spots.Rmd’
>     
>     Error: Vignette re-building failed.
>     Execution halted
> Flavor: r-patched-solaris-x86
> 
> The possibilities are:
> 
> 	• The CRAN machine had an older version of PROJ, it failed to transform the built-in sf dataset
> 	• The CRAN machine was unstable temporally
> For 1, I may need to follow this GitHub issue r-spatial/sf#1419 to resolve the problem. I have to fix the problem before 2021-04-05 to safely retain the package on CRAN.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by emdodwell** [comment]
Exciting!!

**Comment by TengMCing** [comment]
Prepare for release of `spotoroo` 0.1.1:

 - [x] Check that description is informative
 - [x] Check licensing of included files
 - [x] `devtools::build_readme()`
 - [x] `usethis::use_cran_comments()`
 - [x] `devtools::check(remote = TRUE, manual = TRUE)`
 - [x] `devtools::check_win_devel()`
 - [ ] `rhub::check_for_cran()`
 - [ ] `urlchecker::url_check()`
 - [ ] Update cran-comments.md

Submit to CRAN:

 - [x] `usethis::use_version('patch')`
 - [ ] `devtools::submit_cran()`
 - [ ] Approve email
- [ ] Wait for CRAN...

 Accepted 🎉
 - [x] `usethis::use_news_md()`
 - [x] `usethis::use_github_release()`
 - [x] `usethis::use_dev_version()`
 - [x] Update install instructions in README

**Comment by TengMCing** [comment]
released!
