### ISSUE TITLE
Test suite warnings due to updated ggbeeswarm (0.7.1)

### ISSUE THREAD

**Issue by eclarke** [TengMCing/spotoroo#18]
Hi there, I'm pushing a new version of [ggbeeswarm](github.com/eclarke/ggbeeswarm) to CRAN due to changes in the ggplot2 API, and while I was checking its downstream dependencies I noticed that some of these changes changes caused your test suite to start throwing warnings like the following:

```
Warning (test-plot_spotoroo.R:65): plot_spotoroo() works
The `groupOnX` argument of `geom_quasirandom()` is deprecated as of ggbeeswarm 0.7.1.
i ggplot2 now handles this case automatically.
Backtrace:
  1. testthat::expect_silent(...)
       at test-plot_spotoroo.R:65:2
  9. spotoroo::plot_spotoroo(...)
 10. spotoroo::plot_timeline(...)
       at spotoroo/R/plot_spotoroo.R:166:4
 11. spotoroo:::plot_timeline_only_noise(...)
       at spotoroo/R/plot_timeline.R:101:4
 12. ggbeeswarm::geom_quasirandom(...)
       at spotoroo/R/plot_timeline_only_noise.R:15:2
```

The `groupOnX` argument in all of our `geom_*` and `position_*` functions is no longer needed so we're soft-deprecating it- you can safely just remove it from your code at your leisure. From visual comparison between the test results and what's on your website, I believe your plots still render correctly. I just wanted to let you know in case we ever move the groupOnX argument to a hard deprecation or removal.

Best regards,
Erik

**Comment by TengMCing** [comment]
Many thanks for the update. I have tried to remove this argument from my source code, but it does not work anymore. It seems like `geom_quasirandom` thinks the data should be grouped on the X-axis, though I want it to be grouped on the Y-axis. I have also tried to use the `orientation = "y"` argument introduced in `ggplot2 3.3.0` but it is totally ignored by `geom_quasirandom`. 

```r
Ignoring unknown parameters: `orientation`
```

I have to install `ggbeeswarm 0.6.0` to make the code works again.

Do you have any suggestions on how users may specify the grouping behaviour in `geom_quasirandom` without the use of`groupOnX`?
